---
#List down the packages to be installed on ec2_devops here

pakages:
  - oracle-java8-installer
  - httpd
  - tomcat
  - mysql-server
  - telnet-client
  - curl
  - nslookup

#List down the ports to be opened on ec2_devops
ports:
  - '80'
  - '8080'
  - '3066'
  
