---
- name: setup ec2_devops
  hosts: web
  become: yes
  vars_files:
    - packages.yml

  tasks:
    - name: add oracle package repo
      apt_repository:
        repo: ppa:webupd8team/java
        
    - name: install pakages
      apt:
        name: "{{ item }}"
        state: latest
        update_cache: yes
      with_items: "{{ packages }}"
    
    - name: enable all the services
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      with_items: "{{ packages }}"
    
    - name: enable access to ports defined
      ufw:
        rule: allow
        port: "{{ item }}"
        proto: tcp
      with_items: "{{ ports }}"
