---
- name: setup ec2_devops
  hosts: web
  become: yes
  vars_files:
    - config_file.yml

  tasks:
    - name: add oracle package repo
      apt_repository:
        repo: ppa:linuxuprising/java
        
    - name: install services
      apt:
        name: "{{ item }}"
        state: latest
        update_cache: yes
      with_items: "{{ services }}"
      
    - name: install utilities
      apt:
        name: "{{ item }}"
        state: latest
        update_cache: yes
      with_items: "{{ utilities }}"
    
    - name: enable all the services
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      with_items: "{{ services }}"
    
    - name: enable access to ports defined
      ufw:
        rule: allow
        port: "{{ item }}"
        proto: tcp
      with_items: "{{ ports }}"
