---
- name: setup ec2_devops
  hosts: web
  become: yes
  vars_files:
    - "config_file_{{ ansible_facts['distribution'] }}.yml"

  tasks:

# ------- Cannot be used due to license issue -------------#
#    - name: add oracle package repo
#      apt_repository:
#        repo: ppa:linuxuprising/java

    - name: install "{{ utilities }}" on "{{ ansible_facts['distribution'] }}"
      yum:
        name: "{{ utilities }}"
        state: latest
        update_cache: yes
      when: ansible_facts['distribution'] == "RedHat"

    - name: install "{{ utilities }}" on "{{ ansible_facts['distribution'] }}"
      apt:
        name: "{{ utilities }}"
        state: latest
        update_cache: yes
      when: ansible_facts['distribution'] == "Ubuntu"

    - name: install "{{ services }}" on "{{ ansible_facts['distribution'] }}"
      apt:
        name: "{{ services }}"
        state: latest
        update_cache: yes
      when: ansible_facts['distribution'] == "Ubuntu"
 
    - name: install "{{ services }}" on "{{ ansible_facts['distribution'] }}"
      yum:
        name: "{{ services }}"
        state: latest
        update_cache: yes
      when: ansible_facts['distribution'] == "RedHat"    

    - name: enable all the services
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      with_items: "{{ services }}"
      when: item != "mysql-server"

    - name: enable mysql
      service:
        name: mysql
        state: started
        enabled: yes
      with_items: "{{ services }}"
      when: item == "mysql-server"
    
    - name: enable access to ports defined
      ufw:
        rule: allow
        port: "{{ item }}"
        proto: tcp
      with_items: "{{ ports }}"
